"""initial_schema

Revision ID: f665ebe2b266
Revises: 
Create Date: 2026-03-21 22:00:39.619178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f665ebe2b266'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_token', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=False),
    sa.Column('source_patient_id', sa.String(length=256), nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('destination_name', sa.String(length=256), nullable=False),
    sa.Column('destination_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'fetching', 'transforming', 'delivering', 'completed', 'failed', 'retrying', name='transferstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resource_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_created_at'), 'transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_transfers_patient_token'), 'transfers', ['patient_token'], unique=False)
    op.create_index('ix_transfers_patient_token_created', 'transfers', ['patient_token', 'created_at'], unique=False)
    op.create_index(op.f('ix_transfers_status'), 'transfers', ['status'], unique=False)
    op.create_index('ix_transfers_status_created', 'transfers', ['status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patient_token', sa.String(length=64), nullable=False),
    sa.Column('transfer_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=256), nullable=False),
    sa.Column('source_system', sa.String(length=128), nullable=False),
    sa.Column('destination_name', sa.String(length=256), nullable=True),
    sa.Column('resource_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_event_occurred', 'audit_logs', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_outcome_occurred', 'audit_logs', ['outcome', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_token'), 'audit_logs', ['patient_token'], unique=False)
    op.create_index(op.f('ix_audit_logs_transfer_id'), 'audit_logs', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_transfer_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_patient_token'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_outcome_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_event_occurred', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_transfers_status_created', table_name='transfers')
    op.drop_index(op.f('ix_transfers_status'), table_name='transfers')
    op.drop_index('ix_transfers_patient_token_created', table_name='transfers')
    op.drop_index(op.f('ix_transfers_patient_token'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_created_at'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
